# Generated by Django 4.0.6 on 2022-08-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reparacion',
            old_name='Desperfecto',
            new_name='desperfecto',
        ),
        migrations.AddField(
            model_name='reparacion',
            name='descripcion',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
