# Generated by Django 4.0.6 on 2022-08-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_desperfecto_reparacion_desperfecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
