# Generated by Django 4.0.6 on 2022-08-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_reparacion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
