# Generated by Django 4.0.6 on 2022-08-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_reparacion_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='desperfecto',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
