# Generated by Django 4.0.6 on 2022-08-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_cliente_desperfecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='especialidad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
