# Generated by Django 4.0.6 on 2022-08-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
