# Generated by Django 4.0.6 on 2022-08-28 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMensajeria', '0003_respuesta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
