# Generated by Django 4.0.6 on 2022-08-29 00:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMensajeria', '0004_delete_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
