# Generated by Django 4.0.6 on 2022-08-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_mecanico_especialidad'),
        ('appMensajeria', '0006_alter_post_contenido_alter_post_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to='blog.cliente'),
        ),
    ]
