# Generated by Django 4.0.6 on 2022-08-29 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMensajeria', '0007_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
